package io.openems.edge.greenbutton;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "Green Button Import", //
		description = "Imports historic consumption data from a Green Button (ESPI) XML document into a Timedata service.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "greenButton0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Source", description = "Where to read the Green Button XML from")
	Source source() default Source.FILE;

	@AttributeDefinition(name = "File path", description = "Absolute path of the Green Button XML file (Source = FILE)")
	String path() default "";

	@AttributeDefinition(name = "URL", description = "URL of the Green Button XML document (Source = URL)")
	String url() default "";

	@AttributeDefinition(name = "Authorization header", description = "Optional value of the HTTP Authorization header, e.g. 'Bearer <token>' (Source = URL)", type = AttributeType.PASSWORD)
	String authorizationHeader() default "";

	@AttributeDefinition(name = "Target Channel", description = "Channel-Address the imported energy values [Wh] are written to")
	String targetChannel() default "_sum/ConsumptionActiveEnergy";

	@AttributeDefinition(name = "Cumulative", description = "Write cumulative energy [Wh] (like an energy meter counter) instead of the energy per interval")
	boolean cumulative() default true;

	@AttributeDefinition(name = "Power Channel", description = "Optional Channel-Address the average power per interval [W] is written to; empty to disable")
	String powerChannel() default "";

	@AttributeDefinition(name = "Timedata-ID", description = "ID of the Timedata service the data is written to")
	String timedata_id() default "timedata0";

	@AttributeDefinition(name = "Polling interval [h]", description = "Re-import every x hours; 0 imports once on activation", min = "0")
	int pollingIntervalHours() default 24;

	@AttributeDefinition(name = "Timedata target filter", description = "This is auto-generated by 'Timedata-ID'.")
	String timedata_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Green Button Import [{id}]";
}
